use employee_details;

1.WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.;
select ename, sal*12 as 'Annual sal' from emp;

2.WAQTD ENAME AND JOB FOR ALL THE EMPLOYEE WITH THEIR HALF TERM SALARY.;
select ename, job, sal*6 as 'half term sal' from emp;

3.WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH AN ANNUALBONUS OF 2000.;
select ename, sal*12+2000 as 'annual bonus 2000' from emp;

4.WAQTD NAME SALARY AND SALARY WITH A HIKE OF 10%.;
select ename, sal, sal+sal*0.1 as 'sal with 10% hike' from emp;

5.WAQTD NAME AND SALARY WITH DEDUCTION OF 25%.;
select ename, sal-sal*0.25 as 'deduction of 25%' from emp;

6.WAQTD NAME AND SALARY WITH MONTHLY HIKE OF 50.;
select ename , sal+sal*0.5 as ' 50% hike' from emp;

7.WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10%.;
select ename, sal*12-(sal*12)*0.1 from emp;  
select ename, sal*12*0.1 from emp;

8.WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEE (SAL+COMM).;
select * from emp;
select ename, sal+comm  from emp;

9.WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY.;
select *,sal*12 as 'Annual_sal' from emp;

10.WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALTY IN SALARY.;
select ename, job, sal-100 from emp;

/*1.WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SMITH*/
select ename, sal*12 as 'annual sal' from emp
where ename= 'smith' ;

2.WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK;
 select ename,job from emp 
 where job = 'clerk';

3.WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN;
select ename, sal,job from emp 
where job = 'salesman';

4.WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000;
select * from emp 
where sal >2000;

5.WAQTD DETAILS OF THE EMP WHOS NAME IS JONES;
select * from emp
where ename = 'jones';

6.WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01- JAN-81;
select * from emp;
where hiredate >'1981-01-01';

7.WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000;
select ename,sal*12 as 'annual sal' from emp
where sal*12>12000;

8.WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30;
select ename, empno,deptno from emp 
where deptno = 30;

9.WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981;
select ename, hiredate from emp 
where hiredate<1980-12-31;

10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER;
select * from emp
where job = 'Manager';

11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400;
select ename,sal,comm from emp
where comm = '1400';

12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY;
select * from emp 
where comm>sal;

13.WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87;
select empno, hiredate from emp
where hiredate< "1986-12-31";

select * from emp;

14.WAQTD DETAILS OF EMPLOYEES WORKING AS AN N ANALYST;
select * from emp
where job = "analyst";

15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH;
select * from emp
where sal >2000;


ASSIGNMENT ON LOGICAL OPERATORS :
-------------------------------
1.WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500;
select * from emp
where job = "clerk" and sal < 1500;

2.WAQTD NAME AND HIREDATE OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 30;
select ename,hiredate,deptno from emp
where job = "manager" and deptno = "30";

3.WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPT
  30 AS SALESMAN AND THEIR ANNUAL SALARY HAS TO BE GREATER THAN 14000;
  select *, sal*12 as "annual sal" from emp
  where deptno = "30" and job = "salesman" and sal*12>14000;

4.WAQTD ALL THE DETAILS OF THE EMP WORKING IN DEPT 30 OR AS ANALYST;
select * from emp
where deptno = '30' or job = 'analyst';

5.WAQTD NAMES OF THE EMPMLOYEES WHOS SALARY IS LESS THAN 1100 AND THEIR DESIGNATION IS CLERK;
select ename, sal,job from emp
where 

6.WAQTD NAME AND SAL , ANNUAL SAL AND DEPTNO IF DEPTNO IS 20 EARNING MORE THAN 1100 AND ANNUAL SALARY EXCEEDS 12000


7.WAQTD EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPT 20;


8.WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 20 OR 30;
select * from emp
where deptno = '20' or deptno = '30';

9.WAQTD DETAILS OF EMPLOYEES WORKING AS AN ALYST IN DEPT 10;


10.WAQTD DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF RUPEES 4000
11.WAQTD NAMES AND DEPTNO , JOB OF EMPS WORKING AS CLERK IN DEPT 10 OR 20
12.WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN DEPT 10
13.WAQTD NAMES OF EMPLOYEES WORKING IN DEPT 10 , 20 ,30 , 40
14.WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839
15.WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN OR CLERK
16.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87
17.WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000
18.WAQTD NAMES OF EMPLOYEES HIRED AFTER 81 INTO DEPT 10 OR 30
19.WAQTD NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE EMPLOYEES WORKING AS MANAGER OR CLERK INTO DEPT 10 OR 30
20.WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SAL IS BETWEEN 1000 AND 4000 ANNUAL SALARY MORE THAN 15000
21.WAQTD name ,sal and annual salary of all the employees who are Working in dept 20 and  
   has annual salary greater than 10000 but less Than 20000.
22.WAQTD name , sal and deptno of the employees earning 2000 In dept 20 or 30 .
23.WAQTD names of the employees working in dept 10 As a clerk or a manager .
24.WAQTD details of the employees working as 'SALESMAN' or ' ANALYST' in dept 10 or 30 .
25.WAQTD details of all the employees except the employee working as 'Salesman'.
26.WAQTD details of all the employees except the employees Working in dept 10 or 20 .
27.WAQTD name and hiredate of the employees if the employees Are hired during 1987 .
 
ASSIGNMENT ON SPECIAL OPERATORS :
--------------------------------
1)LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
2)LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER
3)LIST ALL THE SALESMEN IN DEPT 30
4)LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500
5)LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘S’ OR ‘A’
6)LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
7)LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH ‘S’
8)LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10
9)LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK
10)LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30
11)LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
12)LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500
13)LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘M’ OR ‘J’
14)LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30
15)LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ‘ES’ OR ‘R’
16)LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY
17)DISPLAY ALL THE EMPLOYEE WHO ARE ‘SALESMAN’S HAVING ‘E’ AS THE LAST BUT ONE CHARACTER IN ENAME BUT SALARY HAVING EXACTLY 4 CHARACTER
18)DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81
19)DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB
20)LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000
21)LIST THE EMPLOYEES WHOSE SALARY NOT IN THE RANGE OF 1000 TO 2000 AND WORKING IN DEPT 10,20 OR 30 EXCEPT ALL SALESMEN
22)LIST THE DEPARTMENT NAMES WHICH ARE HAVING LETTER ‘O’ IN THEIR LOCATIONS AS WELL AS THEIR DEPARTMENT NAMES
23)DISPLAY ALL THE EMPLOYEES WHOSE JOB HAS STRING ‘MAN’ IN IT.
24)LIST THE EMPLOYEES WHO ARE HIRED AFTER 82 AND BEFORE 87.
25)WAQTD ALL THE DETAILS OF EMPLOYEES HIRED IN NOVEMBER AND DECEMBER.
26)LIST ALL THE EMPLOYEE NAMES AND COMISSION FOR THOSE EMPLOYEES WHO EARN COMISSION MORE THAN THEIR SALARY
27)WAQTD NAME AND DESIGNATION FOR ALL THE EMPLOYEES HAVING REPORTING MANAGERS AND ALSO THRIE NAMES STARTING WITH ‘S’
28)WAQTD NAME AND SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY ENDS WITH ‘0’ .
29)WAQTD NAME OF THE EMPLOYEE HAVING ATLEAST 2L’s IN HIS NAME .
30)WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH A ‘VOWEL’
		



